Code Sample for spring_jdbc Getting started
oracle-samples/oracle-db-examples pull request #198
Opened 2022-05-11 22:11 UTC by peterrsongg

This is the accompanying code sample for the spring jdbc getting started video.

2022-05-12 18:10 UTC, Kuassim commented on java/spring_jdbc_example/src/main/java/com/example/demo/Service/StudentService.java
> + The code sample maps uses the jpaRepository to return
Can you rework this sentence?

2022-05-12 18:18 UTC, Kuassim commented on java/spring_jdbc_example/README.md
> +* TestController.java: Has one get mapping that uses StudentService to retrieve all the Students
Can you plz rework this sentence?

2022-05-12 18:19 UTC, Kuassim approved these changes

2022-05-12 18:20 UTC, Kuassim submitted a review, later dismissed

2022-05-19 10:46 UTC, Kuassim approved these changes

2022-05-20 17:39 UTC, gvenzl requested changes

2022-05-20 17:39 UTC, gvenzl commented on java/spring_jdbc_example/src/main/resources/application.properties
> +spring.datasource.url=jdbc:oracle:thin:@adbps_medium?TNS_ADMIN=/Users/psong/Desktop/JDBC_vid_series/Wallet_ADBPS
This should be a placeholder just like we have for username and password.

2024-12-18 16:11 UTC, closed without merging