Adding RSI example
oracle-samples/oracle-db-examples pull request #225
Opened 2022-11-10 16:19 UTC by harayuanwang

2022-11-10 17:12 UTC, jeandelavarene reviewed
Add a copyright to all Java files and Javadoc as well.

2022-11-10 17:13 UTC, Kuassim approved these changes

2022-11-10 17:19 UTC, harayuanwang commented
Working on the copyright and JavaDoc, please do not approve this PR before they're done.

2022-11-10 18:24 UTC, gvenzl requested changes
Please template the connection strings, they currently have real service names in them.

2022-11-10 18:24 UTC, gvenzl commented on java/rsi-example/src/main/java/rsi/example/amqp/Listener.java
> +      "(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.us-phoenix-1.oraclecloud.com))(connect_data=(service_name=gebqqvpozhjbqbs_azuretestdb_high.adb.oraclec
This one should be templated to allow users to fill in their own connection details.
Certainly, we should not have a pre-existing service name in our examples.

2022-11-10 18:24 UTC, gvenzl commented on java/rsi-example/src/main/java/rsi/example/mqtt/Listener.java
> +      "(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.us-phoenix-1.oraclecloud.com))(connect_data=(service_name=gebqqvpozhjbqbs_azuretestdb_high.adb.oraclec
Should be templated

2022-11-10 18:24 UTC, gvenzl commented on java/rsi-example/src/main/java/rsi/example/stomp/Listener.java
> +      "(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.us-phoenix-1.oraclecloud.com))(connect_data=(service_name=gebqqvpozhjbqbs_azuretestdb_high.adb.oraclec
Should be templated

2022-11-10 21:53 UTC, harayuanwang commented
All the comments have been addressed

2022-11-11 02:53 UTC, gvenzl commented
Thanks @harayuanwang. Good to go from my side.

2022-11-12 13:27 UTC, merged