Change to use declarative types with @graphql-tools/schema
oracle-samples/oracle-db-examples pull request #362
Opened 2024-06-13 15:57 UTC by salma-bek

The purpose of this PR is to use declarative types with @graphql-tools/schema instead of GraphQL’s reference implementation

2024-06-14 12:58 UTC, martin-bach-oracle commented on javascript/MLE-Demo/book-schema.mjs
> +      const conn = oracledb.defaultConnection();
please consider using `session.execute()` here.

2024-06-14 12:58 UTC, martin-bach-oracle commented on javascript/MLE-Demo/book-schema.mjs
>    const conn = oracledb.defaultConnection();
please consider using `session.execute()` instead

2024-06-14 12:59 UTC, martin-bach-oracle commented on javascript/MLE-Demo/book-schema.mjs
>    const response = await fetch(`${BASE_URL}${SEARCH_URL}`, { credentials: "include" });
beginning with Oracle Database 23.3 it should no longer be necessary to use `createntials: include`

2024-06-14 13:33 UTC, martin-bach-oracle commented
In addition to the comments in the code, please add instructions how to use rollup to generate a bundle of `graphql-tools` and your code.

2024-06-14 13:35 UTC, martin-bach-oracle requested changes
Kindly address the outstanding comments and resubmit the code for review

2024-12-12 17:59 UTC, gvenzl commented
Closed as per @martin-bach-oracle.

2024-12-12 17:59 UTC, closed without merging