Adds Basic/simplified Resource Provider Code sample
oracle-samples/oracle-db-examples pull request #404
Opened 2024-10-25 23:34 UTC by aberinnj

2024-10-25 23:35 UTC, aberinnj commented
@Kuassim @jeandelavarene Please review, thank you

2024-10-28 16:19 UTC, Kuassim requested changes
In Main.java
I saw a try-catch; why not use a try-with-resource (as in the comment)?
I also saw you are using DriverManager.getConnection instead of using 
OracleDataSource ods = new OracleDataSource();
...
Connection conn = ods.getConnection()

2024-10-28 17:23 UTC, aberinnj commented
Ok fixed!

2024-10-28 17:25 UTC, Kuassim approved these changes

2024-11-05 18:03 UTC, MouhsinElmajdouby commented on java/jdbc-resource-providers/properties/demo-3.properties
> +# Copyright (c) 2023 Oracle and/or its affiliates.
same here

2024-11-06 13:09 UTC, MouhsinElmajdouby commented on java/jdbc-resource-providers/src/main/java/org/oracle/Main.java
> +import java.sql.*;
I think we should import only the needed classes from **java.sql** instead of the whole package

2024-11-06 17:09 UTC, MouhsinElmajdouby approved these changes

2024-11-06 17:16 UTC, jeandelavarene approved these changes

2024-11-06 17:16 UTC, merged